// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/api/proto/booking.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Booking status
type BookingStatus int32

const (
	BookingStatus_PENDING   BookingStatus = 0
	BookingStatus_CONFIRMED BookingStatus = 1
	BookingStatus_CANCELLED BookingStatus = 2
	BookingStatus_COMPLETED BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "CANCELLED",
		3: "COMPLETED",
	}
	BookingStatus_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"CANCELLED": 2,
		"COMPLETED": 3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_booking_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_booking_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{0}
}

// Service type
type ServiceType int32

const (
	ServiceType_HAIRCUT      ServiceType = 0
	ServiceType_BEARD_TRIM   ServiceType = 1
	ServiceType_HAIR_WASH    ServiceType = 2
	ServiceType_FULL_SERVICE ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "HAIRCUT",
		1: "BEARD_TRIM",
		2: "HAIR_WASH",
		3: "FULL_SERVICE",
	}
	ServiceType_value = map[string]int32{
		"HAIRCUT":      0,
		"BEARD_TRIM":   1,
		"HAIR_WASH":    2,
		"FULL_SERVICE": 3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_booking_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_booking_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{1}
}

// Time slot model
type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO format datetime string
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // ISO format datetime string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// Available time slots response
type TimeSlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSlots     []*TimeSlot            `protobuf:"bytes,1,rep,name=time_slots,json=timeSlots,proto3" json:"time_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlotList) Reset() {
	*x = TimeSlotList{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlotList) ProtoMessage() {}

func (x *TimeSlotList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlotList.ProtoReflect.Descriptor instead.
func (*TimeSlotList) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSlotList) GetTimeSlots() []*TimeSlot {
	if x != nil {
		return x.TimeSlots
	}
	return nil
}

// Booking model
type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,3,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO format datetime string
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // ISO format datetime string
	ServiceType   ServiceType            `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3,enum=booking.ServiceType" json:"service_type,omitempty"`
	Status        BookingStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=booking.BookingStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // ISO format datetime string
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO format datetime string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *Booking) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Booking) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Booking) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_HAIRCUT
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_PENDING
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Booking) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// List of bookings
type BookingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingList) Reset() {
	*x = BookingList{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingList) ProtoMessage() {}

func (x *BookingList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingList.ProtoReflect.Descriptor instead.
func (*BookingList) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *BookingList) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

// Create booking request
type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO format datetime string
	ServiceType   ServiceType            `protobuf:"varint,4,opt,name=service_type,json=serviceType,proto3,enum=booking.ServiceType" json:"service_type,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateBookingRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_HAIRCUT
}

func (x *CreateBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// Get booking request
type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Update booking request
type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO format datetime string
	ServiceType   ServiceType            `protobuf:"varint,3,opt,name=service_type,json=serviceType,proto3,enum=booking.ServiceType" json:"service_type,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookingRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateBookingRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_HAIRCUT
}

func (x *UpdateBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// Cancel booking request
type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Cancel booking response
type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get user bookings request
type GetUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsRequest) Reset() {
	*x = GetUserBookingsRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsRequest) ProtoMessage() {}

func (x *GetUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Get barber bookings request
type GetBarberBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // ISO format date string (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarberBookingsRequest) Reset() {
	*x = GetBarberBookingsRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarberBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarberBookingsRequest) ProtoMessage() {}

func (x *GetBarberBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarberBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetBarberBookingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *GetBarberBookingsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *GetBarberBookingsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Get available time slots request
type GetAvailableTimeSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // ISO format date string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableTimeSlotsRequest) Reset() {
	*x = GetAvailableTimeSlotsRequest{}
	mi := &file_pkg_api_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableTimeSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTimeSlotsRequest) ProtoMessage() {}

func (x *GetAvailableTimeSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTimeSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableTimeSlotsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *GetAvailableTimeSlotsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *GetAvailableTimeSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_pkg_api_proto_booking_proto protoreflect.FileDescriptor

const file_pkg_api_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/proto/booking.proto\x12\abooking\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"@\n" +
	"\fTimeSlotList\x120\n" +
	"\n" +
	"time_slots\x18\x01 \x03(\v2\x11.booking.TimeSlotR\ttimeSlots\"\xc6\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbarber_id\x18\x03 \x01(\tR\bbarberId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x127\n" +
	"\fservice_type\x18\x06 \x01(\x0e2\x14.booking.ServiceTypeR\vserviceType\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.booking.BookingStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\";\n" +
	"\vBookingList\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\"\xba\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x127\n" +
	"\fservice_type\x18\x04 \x01(\x0e2\x14.booking.ServiceTypeR\vserviceType\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\x14UpdateBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x127\n" +
	"\fservice_type\x18\x03 \x01(\x0e2\x14.booking.ServiceTypeR\vserviceType\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"&\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x16GetUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x18GetBarberBookingsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"O\n" +
	"\x1cGetAvailableTimeSlotsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date*I\n" +
	"\rBookingStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03*K\n" +
	"\vServiceType\x12\v\n" +
	"\aHAIRCUT\x10\x00\x12\x0e\n" +
	"\n" +
	"BEARD_TRIM\x10\x01\x12\r\n" +
	"\tHAIR_WASH\x10\x02\x12\x10\n" +
	"\fFULL_SERVICE\x10\x032\x8f\x04\n" +
	"\x0eBookingService\x12@\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x10.booking.Booking\x12@\n" +
	"\rUpdateBooking\x12\x1d.booking.UpdateBookingRequest\x1a\x10.booking.Booking\x12N\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponse\x12H\n" +
	"\x0fGetUserBookings\x12\x1f.booking.GetUserBookingsRequest\x1a\x14.booking.BookingList\x12L\n" +
	"\x11GetBarberBookings\x12!.booking.GetBarberBookingsRequest\x1a\x14.booking.BookingList\x12U\n" +
	"\x15GetAvailableTimeSlots\x12%.booking.GetAvailableTimeSlotsRequest\x1a\x15.booking.TimeSlotListB5Z3github.com/ita-av/booking-service/pkg/api/generatedb\x06proto3"

var (
	file_pkg_api_proto_booking_proto_rawDescOnce sync.Once
	file_pkg_api_proto_booking_proto_rawDescData []byte
)

func file_pkg_api_proto_booking_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_booking_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_booking_proto_rawDesc), len(file_pkg_api_proto_booking_proto_rawDesc)))
	})
	return file_pkg_api_proto_booking_proto_rawDescData
}

var file_pkg_api_proto_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_api_proto_booking_proto_goTypes = []any{
	(BookingStatus)(0),                   // 0: booking.BookingStatus
	(ServiceType)(0),                     // 1: booking.ServiceType
	(*TimeSlot)(nil),                     // 2: booking.TimeSlot
	(*TimeSlotList)(nil),                 // 3: booking.TimeSlotList
	(*Booking)(nil),                      // 4: booking.Booking
	(*BookingList)(nil),                  // 5: booking.BookingList
	(*CreateBookingRequest)(nil),         // 6: booking.CreateBookingRequest
	(*GetBookingRequest)(nil),            // 7: booking.GetBookingRequest
	(*UpdateBookingRequest)(nil),         // 8: booking.UpdateBookingRequest
	(*CancelBookingRequest)(nil),         // 9: booking.CancelBookingRequest
	(*CancelBookingResponse)(nil),        // 10: booking.CancelBookingResponse
	(*GetUserBookingsRequest)(nil),       // 11: booking.GetUserBookingsRequest
	(*GetBarberBookingsRequest)(nil),     // 12: booking.GetBarberBookingsRequest
	(*GetAvailableTimeSlotsRequest)(nil), // 13: booking.GetAvailableTimeSlotsRequest
}
var file_pkg_api_proto_booking_proto_depIdxs = []int32{
	2,  // 0: booking.TimeSlotList.time_slots:type_name -> booking.TimeSlot
	1,  // 1: booking.Booking.service_type:type_name -> booking.ServiceType
	0,  // 2: booking.Booking.status:type_name -> booking.BookingStatus
	4,  // 3: booking.BookingList.bookings:type_name -> booking.Booking
	1,  // 4: booking.CreateBookingRequest.service_type:type_name -> booking.ServiceType
	1,  // 5: booking.UpdateBookingRequest.service_type:type_name -> booking.ServiceType
	6,  // 6: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	7,  // 7: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	8,  // 8: booking.BookingService.UpdateBooking:input_type -> booking.UpdateBookingRequest
	9,  // 9: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	11, // 10: booking.BookingService.GetUserBookings:input_type -> booking.GetUserBookingsRequest
	12, // 11: booking.BookingService.GetBarberBookings:input_type -> booking.GetBarberBookingsRequest
	13, // 12: booking.BookingService.GetAvailableTimeSlots:input_type -> booking.GetAvailableTimeSlotsRequest
	4,  // 13: booking.BookingService.CreateBooking:output_type -> booking.Booking
	4,  // 14: booking.BookingService.GetBooking:output_type -> booking.Booking
	4,  // 15: booking.BookingService.UpdateBooking:output_type -> booking.Booking
	10, // 16: booking.BookingService.CancelBooking:output_type -> booking.CancelBookingResponse
	5,  // 17: booking.BookingService.GetUserBookings:output_type -> booking.BookingList
	5,  // 18: booking.BookingService.GetBarberBookings:output_type -> booking.BookingList
	3,  // 19: booking.BookingService.GetAvailableTimeSlots:output_type -> booking.TimeSlotList
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_booking_proto_init() }
func file_pkg_api_proto_booking_proto_init() {
	if File_pkg_api_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_booking_proto_rawDesc), len(file_pkg_api_proto_booking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_booking_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_booking_proto_depIdxs,
		EnumInfos:         file_pkg_api_proto_booking_proto_enumTypes,
		MessageInfos:      file_pkg_api_proto_booking_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_booking_proto = out.File
	file_pkg_api_proto_booking_proto_goTypes = nil
	file_pkg_api_proto_booking_proto_depIdxs = nil
}
